#!/bin/bash
if [ ! -f ${BAMBOO_CAPABILITIES} ]; then
    cp ${INIT_BAMBOO_CAPABILITIES} ${BAMBOO_CAPABILITIES}
fi

if [ -z ${SECURITY_TOKEN+x} ]; then   
    BAMBOO_SECURITY_TOKEN_PARAM=
else 
    BAMBOO_SECURITY_TOKEN_PARAM="-t ${SECURITY_TOKEN}"
fi 
java ${VM_OPTS} -jar ${AGENT_JAR} ${BAMBOO_SERVER} ${BAMBOO_SECURITY_TOKEN_PARAM}